--- #YAML:1.0
name:                File-Searcher-Similars
version:             1.22
abstract:            ~
license:             ~
author:              
    - Tong Sun <suntong@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Accessor:               0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
